language: python

python: 3.6

stages:
  - test
  - build
  - deploy

before_install:
  - pip install codecov

install:
  - pip install .

script:
  - python setup.py test

after_success:
  - codecov

jobs:
  include:
    - stage: test
    - name: "lint"
      script:
        - python setup.py lint || exit $(($? & 35))
    - name: "twine check"
      before_install:
        - pip install docutils twine
      before_script:
        - python setup.py sdist
      script:
        - twine check dist/*
    - python: 3.5
    - python: 3.7
      dist: xenial
    - stage: build
      name: "sdist"
      script:
        - python setup.py sdist
    - name: "bdist_wheel"
      install:
        - pip install . wheel
      script:
        - python setup.py bdist_wheel
    - name: "sphinx docs"
      install:
        - pip install .["docs"]
      script:
        - sphinx-build docs/ build/
    - stage: deploy
    - name: "pypi"
      deploy:
        provider: pypi
        user: nklapste
        password:
          secure: CF4K63KQgoOwxi6QTvq5vmnJ3jON9iErHsbHEtlU8q2Yf0yKLZ/afFbZlrC14RQDxVvI3oX9SGEgJh0O73j1Kw1LH9AyBxIuT7+YtEX3eBiMPIVkK1nU8hc8uly4JKr9AArikFbCy9BJzyHzk92PmA8DzVYistnLy3WD5g/1JjG2GV+jGHZrUSdZxPTbQCpwgj3WFpsj6eTlJcUvotF70ea4SeF32ptPqJadEsV2bVHiQft6VuPHoWTcsCGKPoR2vM/DPvM7ar81QIDyBGC1s1hO9LSYYnXOA0zp0nXO/hw2CnbJNwYf/xG6uwFVtizi7ag18AGcjUrCMZpP++bDbBnRqR8NbE3dnNCdA+s8uwRBeCOk3D5NUQGr6lBUUY6g3CpY1dVJ63zy2AjukIHnPKWxYggQLdCStUjOBNMG44YNp2keoVUSetAiYwTOi6RXTIfjQ6QFGLPQdEhofQf7iZ3tn2m9xI7twOuxRczE0e9lOwdmIxSfBYQSTlhD0kpWpS2jha+Wtgu/nFyialD/0EiF39jodh4+Mpi9PfpvFizPGF0r4ck9jUkylnEYDSjVLarxRgdBxv7Mo2ClQwIpS/jh8vHuXH6227MsA12w2Xe/XZzXKjx7Ui2zli/fo4GYb3dDoR+wKS04nwLHWEA1lGge4HzO3HiLYdBuSqyN4qE=
        on:
          tags: true
          branch: master
          repo: nklapste/ghast
        distributions: "sdist bdist_wheel"