language: python

python: 3.6

stages:
  - test
  - build
  - deploy

before_install:
  - pip install codecov

install:
  - pip install .

script:
  - python setup.py test

after_success:
  - codecov

jobs:
  include:
    - stage: test
    - name: "lint"
      script:
        - python setup.py lint || exit $(($? & 35))
    - name: "twine check"
      before_install:
        - pip install docutils twine
      before_script:
        - python setup.py sdist
      script:
        - twine check dist/*
    - python: 3.5
    - python: 3.7
      dist: xenial
    - stage: build
      name: "sdist"
      script:
        - python setup.py sdist
    - name: "bdist_wheel"
      install:
        - pip install . wheel
      script:
        - python setup.py bdist_wheel
    - name: "sphinx docs"
      install:
        - pip install .["docs"]
      script:
        - sphinx-build docs/ build/
    - stage: deploy
      deploy:
        provider: pypi
        user: nklapste
        password:
          secure: CF4K63KQgoOwxi6QTvq5vmnJ3jON9iErHsbHEtlU8q2Yf0yKLZ/afFbZlrC14RQDxVvI3oX9SGEgJh0O73j1Kw1LH9AyBxIuT7+YtEX3eBiMPIVkK1nU8hc8uly4JKr9AArikFbCy9BJzyHzk92PmA8DzVYistnLy3WD5g/1JjG2GV+jGHZrUSdZxPTbQCpwgj3WFpsj6eTlJcUvotF70ea4SeF32ptPqJadEsV2bVHiQft6VuPHoWTcsCGKPoR2vM/DPvM7ar81QIDyBGC1s1hO9LSYYnXOA0zp0nXO/hw2CnbJNwYf/xG6uwFVtizi7ag18AGcjUrCMZpP++bDbBnRqR8NbE3dnNCdA+s8uwRBeCOk3D5NUQGr6lBUUY6g3CpY1dVJ63zy2AjukIHnPKWxYggQLdCStUjOBNMG44YNp2keoVUSetAiYwTOi6RXTIfjQ6QFGLPQdEhofQf7iZ3tn2m9xI7twOuxRczE0e9lOwdmIxSfBYQSTlhD0kpWpS2jha+Wtgu/nFyialD/0EiF39jodh4+Mpi9PfpvFizPGF0r4ck9jUkylnEYDSjVLarxRgdBxv7Mo2ClQwIpS/jh8vHuXH6227MsA12w2Xe/XZzXKjx7Ui2zli/fo4GYb3dDoR+wKS04nwLHWEA1lGge4HzO3HiLYdBuSqyN4qE=
        on:
          tags: true
          branch: master
          repo: nklapste/ghast
        distributions: "sdist bdist_wheel"
    - name: "docker"
      before_deploy:
        - docker build -t nklapste/ssswms:$TRAVIS_TAG .
      deploy:
        provider: script
        script: sh $TRAVIS_BUILD_DIR/scripts/deploy.sh
        on:
          tags: true
          branch: master
          repo: nklapste/ghast

env:
  global:
    - secure: 0ovkSj+s1ianqrNmbxpQcXOjfCM4R0C9r2T5Y6JjJHt5Af9mOZRbfxSFZrpX7pDwt50J9RulmsKdpk2BzxJW40bhBqOz33QIBaWKgasL0dwt2WXQuv1JcHCN3iq6UQOIQW4Lg+Y2+U7Hsc11c9v2gcL1QAmG7TuaD4389OZIZasGohBUP7dMx7Rp/FfDPBKER+Netq+HA0gEEcVixdWWsLStbBKuX6EaH/foD5npkf4gi+3FbRauCaCJzsy5e8aaUyEi1BdceXx/o2mb6G4h8rJdRMFvC70chrEyMlrCOu26GoqZpxeWbkSqmDo4iJlzg/PnMQWebbrGja72Mcacq9WA1IFbiLpmHmPqJhGpQzyC4XF31VYSBG9SqyZc9iKe/EZPB1m6VjICsGMI+yUW2MWMH2d871NjYRTxHz5NJfS5Uqy65b+LsPSB+e2mJjP33YQvHOe22w6OkExalMd4YKg7BNnEjKTxcG9k9K50ESVADCRwoADPPaTcui0gg40bK5gnW5c+VWOviWsTwYA0C+tzKFpWoWb9SZtklwZxH5Gz8YJxsLil9DjZKKymZHcAJ5m+Wo9Y9/PqYs9zkTGRbMAb7FTT93p1Fg10LIH2MLxPpmbnQpXljFC/5HLsAtEoILvEZdWjZiWCOuNHR6roHgweR7w3qyyA5/m3Yd8wuls=
    - secure: qZiNssSqbOjhorkMiernB/5dqAXApFXripbRkoAjZ/lfZ0+fpqs872ptd6QPMXDYlBUMy6stQeGVAz2URRwzvrZuGYC9+7SCdLC6KV22felSYCZ0J6A2QxE7b3ns24MsfjITaX7Mgpzrvn9F7x8qelMpV5lxTDYRogQ1Bcr3QtP5jsfH1ilKD2eHnDfMAUZ/AcMKtzG2NEepOvQeRY6TQ4ReTCGNkAkMrxIE0xbq39X4Iqp9YakVJCmHKq+8Hcy0Xe3avL4lo/p65tQSDbzkxJ18weX6raIHGDKRtzVXuZXthR5fZQ9uDFqQvo8RwzM/K++e9HJWfRMP0Q7pVmCsALYUu8gBN6d6lDQ1jG9G4/kvwvjBbsqC9os0wo/sstkYf1XGWkycJlkZwQlglTpDROjU2wOiblUmEV9PSCdOaIG/IMSY2O204it77G1qBfzNgom9JdzffFEWqezJ/0LaGfItPYPinR+lugPfYk+p0r8GvYi/1OCgDPa9m8+olAP3H2JU/4C8GW2/NJwkuTiwB2b2AR1CFY4Thrv9vnvhW79DcG2s4k8JXH+XO/EZuVjZiSN0/tZIdA4JE/4tlS97NfkVBdj1diQOEhcUzfIbx/sXvjsgiel13MhYCYbEvKsxdTVkgXO+7IBX23zIYVqGAqXRBpgWo01bTYlkSGslxao=
    - secure: sdbeZjr12UdSELv0GPWxj+w3zx08WwAj6rN1rMhZSFNFyDsN1mWTC8++mlsRA+b8rBZhPu7PMz5gwep5OufMqXnJp/7PH/JARaybHH+eKdCza0MJPOxSmBOP0XN97AaM6s/qvxHLZ5Yjq09HK7B1rc15jxnlrYku9zCQnp79jr/oPMgbG44CfrYTKVAcrmfcDpfvehJS2XVT1MNhFRI5GPw7LeZycW3hMt3AqI57ds2dh4l2lzLyS+jZJIn047BuhSfuCfJA4vFwitUjdj6K9RJCfz4J9J1WEDHuIxvPoIi7nGmmLTDiiBgrkoBRPty8L/2/mVp6HM6txrsnt7FNzPU+Wf0djtxC7Zt2F0EeZbCqpevcRVG4LGTn1ilmgcnyeE8ShTlfX4cysMjO3jXi07tOdlokqz77uCJ1NlnszldM1GtVccRXVQZrqLaKLwZlgA4XHGvCiotnr6Z/QdewW4+LVy8w6OvaWjKfinHIWfTD/J6BN/A02ZKh/1DxqLQk+qKCJxeD3KuyXLJ+NLqcXz4OlcL+t49Qi4Cu0QqTD0p3SlJFoaUCLAwBdKe9JHzbNGbBAh/49wc3e76NiFsirU8qpWO/ns6rZ7sRmwXLhj6zSghVBQgXWB3gtMzqNwXAjmuxLVEjdTdmEa35aGJ+nmsOn01jxLBJtVk6tfh0KdE=
