version: '3'

# example docker-compose.yml for setup of ghast
# fill in as needed

services:
  web:
    image: nklapste/ghast:latest
    ports:
      - "8989:8989"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./target_script:/app/target_script
    command: --verbose --host=0.0.0.0 --port=8989 --alert-script=/app/target_script --alert-url=/foobar
    deploy:
      placement:
        constraints: [node.role == manager]